### ISSUE TITLE
Segfault in drizzle 1.14.x

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzle#118]
I'm seeing a very consistent segfault in `drizzle` for all 1.14.x versions, which also means it happens for all `jwst` 1.12.x versions as well, which require this version of `drizzle`.  I.e. the current release.  To reproduce:

```python
from astroquery.mast import Observations
from jwst.step import ResampleStep


filename = "jw01345002001_14201_00001_nrcalong_cal.fits"
uri = f"mast:JWST/product/{filename}"
Observations.download_file(uri)

result = ResampleStep.call(filename)
```

and the result:

```
2023-09-28 16:26:11,835 - stpipe.ResampleStep - INFO - ResampleStep instance created.
2023-09-28 16:26:12,042 - stpipe.ResampleStep - INFO - Step ResampleStep running with args ('jw01345002001_14201_00001_nrcalong_cal.fits',).
2023-09-28 16:26:12,043 - stpipe.ResampleStep - INFO - Step ResampleStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'weight_type': 'ivm', 'output_shape': None, 'crpix': None, 'crval': None, 'rotation': None, 'pixel_scale_ratio': 1.0, 'pixel_scale': None, 'output_wcs': '', 'single': False, 'blendheaders': True, 'allowed_memory': None, 'in_memory': True}
2023-09-28 16:26:12,309 - stpipe.ResampleStep - INFO - Using drizpars reference file: /data/beegfs/astro-storage/groups/jwst/common/crds_cache/jwst_ops/references/jwst/nircam/jwst_nircam_drizpars_0001.fits
2023-09-28 16:26:12,341 - stpipe.ResampleStep - INFO - Driz parameter kernel: square
2023-09-28 16:26:12,341 - stpipe.ResampleStep - INFO - Driz parameter pixfrac: 1.0
2023-09-28 16:26:12,341 - stpipe.ResampleStep - INFO - Driz parameter fillval: INDEF
2023-09-28 16:26:12,341 - stpipe.ResampleStep - INFO - Driz parameter weight_type: ivm
2023-09-28 16:26:12,342 - stpipe.ResampleStep - INFO - Output pixel scale ratio: 1.0
2023-09-28 16:26:12,488 - stpipe.ResampleStep - INFO - Resampling science data
2023-09-28 16:26:15,795 - stpipe.ResampleStep - INFO - Drizzling (2048, 2048) --> (2068, 2075)
Segmentation fault
```

It is segfaulting on CentOS Linux release 7.9.2009 (Core), and the system info of the machine:

```python
In [1]: import platform; print(platform.platform())
   ...: import sys; print("Python", sys.version)
   ...: import astropy; print("astropy", astropy.__version__)
   ...: import numpy; print("Numpy", numpy.__version__)
   ...: import drizzle; print("drizzle", drizzle.__version__)
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
astropy 5.3.3
Numpy 1.25.2
drizzle 1.14.2
```

It runs fine on the following (no segfault) on the same machine with drizzle 1.13.7:

```python
In [1]: import platform; print(platform.platform())
   ...: import sys; print("Python", sys.version)
   ...: import astropy; print("astropy", astropy.__version__)
   ...: import numpy; print("Numpy", numpy.__version__)
   ...: import drizzle; print("drizzle", drizzle.__version__)
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
astropy 5.3.3
Numpy 1.25.2
drizzle 1.13.7
```

No segfaults at all on my Mac laptop.

**Comment by jdavies-st** [comment]
I also ran `git bisect`, and it appears the bug was introduced here

```
$ git bisect bad
5618520d77feca11163e5859982308b15e8c5bed is the first bad commit
commit 5618520d77feca11163e5859982308b15e8c5bed
Author: Mihai Cara <mihail.cara@gmail.com>
Date:   Sun Jul 9 17:35:55 2023 -0400

    Do not error on invalid pixmap for polygon intersection

 src/cdrizzlebox.c  | 1394 ++++++++++++++++++++++++----------------------------
 src/cdrizzlemap.c  |  156 +++---
 src/cdrizzlemap.h  |   18 +-
 src/cdrizzleutil.h |   33 +-
 4 files changed, 746 insertions(+), 855 deletions(-)
```

**Comment by jdavies-st** [comment]
So I compiled the drizzle C extension in debug mode

```python
$ git diff
diff --git a/setup.py b/setup.py
index 62a586c..cc31bb8 100755
--- a/setup.py
+++ b/setup.py
@@ -22,6 +22,7 @@ def get_extensions():
         'include_dirs': [],
         'libraries': [],
         'define_macros': [],
+        'extra_compile_args': ["-g"],
     }
     cfg['include_dirs'].append(numpy.get_include())
     cfg['include_dirs'].append(srcdir)
```

And then ran the unit tests under gdb, and get the same (probably) segfault:

```
$ gdb -ex run -ex bt -ex quit --args python -m pytest
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/jdavies/miniconda3/envs/drizzle/bin/python3.11...
<snip>
========================================================================= test session starts =========================================================================
platform linux -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/jdavies/dev/drizzle
configfile: pyproject.toml
plugins: jwst-1.12.1, cov-4.1.0, asdf-2.15.1
collected 48 items                                                                                                                                                    

drizzle/tests/test_cdrizzle.py 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7158f63 in setbuffer () from /lib64/libc.so.6
#0  0x00007ffff7158f63 in setbuffer () from /lib64/libc.so.6
#1  0x00007fff4e10ca3a in driz_log_init (handle=<optimized out>) at /home/jdavies/dev/drizzle/src/cdrizzleutil.h:210
#2  driz_log_message (message=0x7fff4e117a84 "starting do_kernel_square") at /home/jdavies/dev/drizzle/src/cdrizzleutil.h:223
#3  do_kernel_square (p=p@entry=0x1649030) at /home/jdavies/dev/drizzle/src/cdrizzlebox.c:857
#4  0x00007fff4e1146e8 in utest_cdrizzle (argc=argc@entry=1, argv=argv@entry=0x7fffffffb830) at /home/jdavies/dev/drizzle/src/tests/utest_cdrizzle.c:806
#5  0x00007fff4e105f4a in test_cdrizzle (self=<optimized out>, args=<optimized out>) at /home/jdavies/dev/drizzle/src/cdrizzleapi.c:440
#6  0x0000000000525f30 in cfunction_call ()
#7  0x0000000000502d54 in _PyObject_MakeTpCall.localalias ()
#8  0x000000000050f025 in _PyEval_EvalFrameDefault ()
#9  0x0000000000535103 in _PyFunction_Vectorcall ()
#10 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#11 0x0000000000535103 in _PyFunction_Vectorcall ()
#12 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#13 0x0000000000535103 in _PyFunction_Vectorcall ()
#14 0x0000000000506418 in _PyObject_FastCallDictTstate.localalias ()
#15 0x000000000053cf46 in _PyObject_Call_Prepend ()
#16 0x000000000060d273 in slot_tp_call ()
#17 0x0000000000502d54 in _PyObject_MakeTpCall.localalias ()
#18 0x000000000050f025 in _PyEval_EvalFrameDefault ()
#19 0x0000000000535103 in _PyFunction_Vectorcall ()
#20 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#21 0x0000000000535103 in _PyFunction_Vectorcall ()
#22 0x0000000000506418 in _PyObject_FastCallDictTstate.localalias ()
#23 0x000000000053cf46 in _PyObject_Call_Prepend ()
#24 0x000000000060d273 in slot_tp_call ()
#25 0x000000000053f2fc in PyObject_Call ()
#26 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#27 0x0000000000535103 in _PyFunction_Vectorcall ()
#28 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#29 0x0000000000535103 in _PyFunction_Vectorcall ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64
---Type <return> to continue, or q <return> to quit---
#30 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#31 0x0000000000535103 in _PyFunction_Vectorcall ()
#32 0x0000000000506418 in _PyObject_FastCallDictTstate.localalias ()
#33 0x000000000053cf46 in _PyObject_Call_Prepend ()
#34 0x000000000060d273 in slot_tp_call ()
#35 0x0000000000502d54 in _PyObject_MakeTpCall.localalias ()
#36 0x000000000050f025 in _PyEval_EvalFrameDefault ()
#37 0x0000000000535103 in _PyFunction_Vectorcall ()
#38 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#39 0x0000000000535103 in _PyFunction_Vectorcall ()
#40 0x0000000000506418 in _PyObject_FastCallDictTstate.localalias ()
#41 0x000000000053cf46 in _PyObject_Call_Prepend ()
#42 0x000000000060d273 in slot_tp_call ()
#43 0x0000000000502d54 in _PyObject_MakeTpCall.localalias ()
#44 0x000000000050f025 in _PyEval_EvalFrameDefault ()
#45 0x0000000000535103 in _PyFunction_Vectorcall ()
#46 0x0000000000512d5a in _PyEval_EvalFrameDefault ()
#47 0x0000000000535103 in _PyFunction_Vectorcall ()
#48 0x0000000000506418 in _PyObject_FastCallDictTstate.localalias ()
#49 0x000000000053cf46 in _PyObject_Call_Prepend ()
#50 0x000000000060d273 in slot_tp_call ()
#51 0x0000000000502d54 in _PyObject_MakeTpCall.localalias ()
#52 0x000000000050f025 in _PyEval_EvalFrameDefault ()
#53 0x00000000005c82ce in _PyEval_Vector ()
#54 0x00000000005c79cf in PyEval_EvalCode ()
#55 0x00000000005e1623 in builtin_exec ()
#56 0x000000000051c107 in cfunction_vectorcall_FASTCALL_KEYWORDS ()
#57 0x000000000051bff1 in PyObject_Vectorcall ()
#58 0x000000000050f025 in _PyEval_EvalFrameDefault ()
#59 0x0000000000535103 in _PyFunction_Vectorcall ()
#60 0x00000000005f343f in pymain_run_module ()
#61 0x00000000005f2e4a in Py_RunMain.localalias ()
#62 0x00000000005b6e19 in Py_BytesMain ()
#63 0x00007ffff710a555 in __libc_start_main () from /lib64/libc.so.6
#64 0x00000000005b6c6f in _start ()
A debugging session is active.

	Inferior 1 [process 266838] will be killed.
```

Hopefully this helps.
